version: "3.9"

volumes:
  adey_backend_db_data: {}

services:
  db:
    container_name: adey_db
    image: adey_db
    build: ./devops/docker/postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${DOCKER_POSTGRES_PORT}:5434"
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_locks_per_transaction=1024
    volumes:
      - adey_backend_db_data:/var/lib/postgresql/data
    networks:
      - adey_network

  broker:
    image: rabbitmq:3-management
    hostname: rabbit1
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    networks:
      - adey_network

  adey_backend:
    image: adey_backend
    container_name: adey_backend
    build:
      dockerfile: ./devops/docker/python/Dockerfile
      context: ./
    restart: on-failure
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/frontend
      - /usr/src/app/chat_widget
    networks:
      - adey_network
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

  celery_worker:
    container_name: adey_celery
    restart: on-failure
    build:
      dockerfile: ./devops/docker/python/Dockerfile
      context: ./
    command: celery -A adey worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/frontend
      - /usr/src/app/chat_widget
      - /usr/src/app/venv
    depends_on:
      - db
      - broker
      - adey_backend
    networks:
      - adey_network

  adey_frontend:
    image: adey_frontend
    container_name: adey_frontend
    build:
      dockerfile: ./devops/docker/nextjs/Dockerfile
      context: .
    restart: always
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - adey_backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - adey_network

networks:
  adey_network:
    ipam:
      driver: default
