# Generated by Django 4.2.8 on 2023-12-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Chat name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('assistant_name', models.CharField(max_length=256, verbose_name='Assistant name')),
                ('assistant_description', models.TextField(verbose_name='Assistant description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('document', models.FileField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rag.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256, verbose_name='Session ID')),
                ('username', models.CharField(default='Anonymous', max_length=128, verbose_name='Username')),
                ('inquiry', models.TextField(verbose_name='User inquiry')),
                ('response', models.TextField(verbose_name='AI response')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rag.chat')),
            ],
        ),
    ]
