# Generated by Django 4.2.8 on 2023-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='unique_together_slug_and_user'),
        ),
    ]
