# Generated by Django 4.2.8 on 2023-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chat_unique_together_slug_and_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
