# Generated by Django 4.2.8 on 2023-12-25 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_chat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Identifier'),
        ),
    ]
