# Generated by Django 4.2.8 on 2024-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_chat_assistant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='business_name',
            field=models.CharField(default='', max_length=256, verbose_name='Business name'),
            preserve_default=False,
        ),
    ]
