# Generated by Django 4.2.8 on 2024-01-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_chat_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='assistant_description',
            new_name='business_description',
        ),
    ]
