# Generated by Django 4.2.8 on 2024-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0010_rename_assistant_description_chat_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='business_description',
            field=models.TextField(verbose_name='Business description'),
        ),
    ]
