# Generated by Django 4.2.8 on 2024-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0011_alter_chat_business_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=300)),
            ],
        ),
    ]
