# Generated by Django 4.2.8 on 2024-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0013_chat_assistant_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='assistant_role',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
