# Generated by Django 4.2.8 on 2024-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0015_resource_document_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('slug', 'chat'), name='unique_together_slug_and_chat'),
        ),
    ]
