# Generated by Django 4.2.8 on 2024-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0018_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='intro_text',
            field=models.TextField(default='Hello! How can I assist you today?'),
        ),
    ]
