# Generated by Django 4.2.8 on 2024-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0019_chat_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('prepared', 'PREPARED'), ('ready', 'READY'), ('finished', 'FINISHED'), ('failed', 'FAILED')], default='prepared', max_length=8, verbose_name='Status'),
        ),
    ]
