# Generated by Django 4.2.8 on 2025-03-19 12:22

from django.db import migrations
from django.conf import settings

from langgraph.checkpoint.postgres import PostgresSaver


def setup_postgres_saver_checkpointer(apps, schema_editor):
    with PostgresSaver.from_conn_string(f"{settings.PG_VECTOR_DB_URL}?sslmode=disable") as checkpointer:
        checkpointer.setup()

class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0020_chat_status'),
    ]

    operations = [
        migrations.RunPython(setup_postgres_saver_checkpointer, reverse_code=migrations.RunPython.noop),  # This migration does not alter the database schema.
    ]
