# Generated by Django 4.2.8 on 2025-05-09 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0021_setup_postgres_memory_checkpointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('preferences', models.JSONField(default=dict, verbose_name='Preferences')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
