# Generated by Django 4.2.8 on 2025-05-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0022_widgetpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='widget_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag.widgetpreference'),
        ),
    ]
