# Generated by Django 4.2.8 on 2025-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0023_chat_widget_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('tool_type', models.CharField(choices=[('rag', 'Retrieval Augmented Generation'), ('api', 'API Call'), ('aps', 'Appointment Scheduler')], default='rag', max_length=3)),
                ('tool_path', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
