# Generated by Django 4.2.8 on 2025-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0024_agenttool'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tools',
            field=models.ManyToManyField(blank=True, to='rag.agenttool'),
        ),
    ]
