# Generated by Django 4.2.8 on 2025-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0025_chat_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='document_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'TXT'), ('CSV', 'CSV'), ('HTML', 'HTML'), ('JSON', 'JSON'), ('MD', 'MD'), ('URL', 'URL')], default='TXT', max_length=5),
        ),
    ]
