# Generated by Django 4.2.8 on 2025-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0025_chat_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='business_description',
            field=models.TextField(blank=True, verbose_name='Business description'),
        ),
    ]
