# Generated by Django 4.2.8 on 2025-11-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0026_alter_resource_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanHandOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=256, verbose_name='Session ID')),
                ('is_handoff', models.BooleanField(default=False, verbose_name='Is Handoff')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rag.chat', verbose_name='Bot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='humanhandoff',
            constraint=models.UniqueConstraint(fields=('session_id', 'bot'), name='unique_together_session_and_bot'),
        ),
    ]
