# Generated by Django 4.2.8 on 2024-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Plan Name')),
                ('period', models.CharField(choices=[('yearly', 'yearly'), ('monthly', 'monthly')], verbose_name='Plan Period')),
                ('max_chatbot', models.IntegerField()),
                ('max_webapp_per_bot', models.IntegerField()),
                ('max_request_per_month', models.IntegerField()),
                ('max_user_session', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
