# Generated by Django 4.2.8 on 2024-02-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('canceled', 'canceled'), ('active', 'active')], default='active', max_length=8)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=256, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=256, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.plan', verbose_name='Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
