# Generated by Django 4.2.8 on 2024-02-05 07:22

import adey_apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(default=adey_apps.users.models.get_default_subscription, on_delete=django.db.models.deletion.CASCADE, to='users.subscription', verbose_name='Subscription'),
        ),
    ]
