# Generated by Django 4.2.8 on 2024-02-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_plan_name_plan_unique_together_name_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
