# Generated by Django 4.2.8 on 2024-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Stripe price id'),
        ),
    ]
