# Generated by Django 4.2.8 on 2024-02-09 22:04

from django.db import migrations
from uuid import uuid4

def populate_identifier(apps, schema_editor):
    Plan = apps.get_model("users", "Plan")
    for plan in Plan.objects.all():
        plan.identifier = uuid4()
        plan.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_plan_identifier'),
    ]

    operations = [
        migrations.RunPython(populate_identifier, reverse_code=migrations.RunPython.noop),
    ]
