# Generated by Django 4.2.8 on 2024-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_identifier_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
