# Generated by Django 4.2.8 on 2024-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscription_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paypal_price_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Paypal price id'),
        ),
    ]
