# Generated by Django 4.2.8 on 2024-02-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_subscriptionorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='verified',
        ),
    ]
