# Generated by Django 4.2.8 on 2024-02-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_stripe_subscription_id_subscription_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='plan',
        ),
    ]
