# Generated by Django 4.2.8 on 2024-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_emailverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationlog',
            name='token_type',
            field=models.CharField(choices=[('email-verification', 'email-verification'), ('password-reset', 'password-reset')], default='email-verification', max_length=18),
        ),
    ]
