# Generated by Django 4.2.8 on 2024-03-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_emailverificationlog_token_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerificationLog',
            new_name='TokenGenerationLog',
        ),
    ]
