# Generated by Django 4.2.8 on 2025-11-02 13:47

import adey_apps.adey_commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_emailverificationlog_tokengenerationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=adey_apps.adey_commons.utils.get_user_avatar_upload_path),
        ),
    ]
