name: Adey CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create test environment file
        run: ./.github/scripts/gen-env.sh

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.staging.yml build

      - name: Run Docker containers
        run: docker compose -f docker-compose.staging.yml up -d

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 Automated release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Adey
            git pull
            docker compose -f docker-compose.prod.yml up -d
